// <auto-generated />
using DemoCrudWithEF.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoCrudWithEF.Domain.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20260826142144_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoCrudWithEF.Domain.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<int>("GroupeId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(130)");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.ToTable("Album", null, t =>
                        {
                            t.HasCheckConstraint("CK_Album_Annee", "Annee >= 1888");

                            t.HasCheckConstraint("CK_Album_Titre", "LEN(TRIM(Titre)) > 0");
                        });
                });

            modelBuilder.Entity("DemoCrudWithEF.Domain.Entities.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(75)");

                    b.HasKey("Id");

                    b.ToTable("Groupe", (string)null);
                });

            modelBuilder.Entity("DemoCrudWithEF.Domain.Entities.Album", b =>
                {
                    b.HasOne("DemoCrudWithEF.Domain.Entities.Groupe", "Groupe")
                        .WithMany("Albums")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("DemoCrudWithEF.Domain.Entities.Groupe", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
